/**
 * Barrel de pantallas base (cliente por defecto).
 * Agrega aquí una línea por cada nueva pantalla que se cree en screens/.
 */
export { default as LoginScreen }                 from './LoginScreen'
export { default as RegisterScreen }              from './RegisterScreen'
export { default as ForgotPasswordScreen }        from './ForgotPasswordScreen'
export { default as OnboardingScreen }            from './OnboardingScreen'
export { default as HomeScreen }                  from './HomeScreen'
export { default as CredencialesScreen }          from './CredencialesScreen'
export { default as NotificationsScreen }         from './NotificationsScreen'
export { default as PerfilMenuScreen }            from './PerfilMenuScreen'
export { default as EnrolamientosScreen }         from './EnrolamientosScreen'
export { default as HistorialAtencionScreen }     from './HistorialAtencionScreen'
export { default as CosegurosPendientesScreen }   from './CosegurosPendientesScreen'
export { default as SolicitudAutorizacionScreen } from './SolicitudAutorizacionScreen'
export { default as MisAutorizacionesScreen }     from './MisAutorizacionesScreen'
export { default as AutorizacionDetalleScreen }   from './AutorizacionDetalleScreen'
export { default as CartillaHubScreen }           from './CartillaHubScreen'
export { default as CartillaMapScreen }           from './CartillaMapScreen'
export { default as PrestadorDetalleScreen }      from './PrestadorDetalleScreen'
export { default as FarmaciasScreen }             from './FarmaciasScreen'
export { default as FarmaciaDetalleScreen }       from './FarmaciaDetalleScreen'
export { default as DelegacionesScreen }          from './DelegacionesScreen'
export { default as DelegacionDetalleScreen }     from './DelegacionDetalleScreen'
export { default as InfoUtilScreen }              from './InfoUtilScreen'
export { default as AyudaScreen }                 from './AyudaScreen'
export { default as NotificationPreferencesScreen } from './NotificationPreferencesScreen'
